# Generated by Django 4.2.11 on 2025-04-21 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='womanuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
