# Generated by Django 4.2.11 on 2025-04-22 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maa', '0002_womanuser_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_slot', models.CharField(choices=[('MORNING', 'Morning'), ('NOON', 'Noon'), ('EVENING', 'Evening'), ('NIGHT', 'Night')], max_length=10)),
                ('description', models.TextField(help_text='What you ate or drank')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'time_slot'],
            },
        ),
    ]
